/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActiveCard: typeof import('./src/components/ActiveCard.vue')['default']
    ArrowCard: typeof import('./src/components/ArrowCard.vue')['default']
    FloatingPanel: typeof import('./src/components/FloatingPanel.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SportCard: typeof import('./src/components/SportCard.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanIcon: typeof import('vant/es')['Icon']
    VanProgress: typeof import('vant/es')['Progress']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    ViewCard: typeof import('./src/components/ViewCard.vue')['default']
  }
}
